import { bigint, boolean, date, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const entryType=pgEnum("entry_type",["initial_capital","income","expense","asset","deposit","refund"]);
export const taxMode=pgEnum("tax_mode",["included","added","exempt"]);
export const entryStatus=pgEnum("entry_status",["active","void"]);

export const businesses=pgTable("businesses",{id:uuid("id").primaryKey().defaultRandom(),name:text("name").notNull(),rut:text("rut"),currency:text("currency").notNull().default("CLP"),timezone:text("timezone").notNull().default("America/Santiago"),active:boolean("active").notNull().default(true),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()});
export const profiles=pgTable("profiles",{id:uuid("id").primaryKey(),email:text("email").notNull(),displayName:text("display_name"),isSuperadmin:boolean("is_superadmin").notNull().default(false),active:boolean("active").notNull().default(true),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()});
export const businessAdmins=pgTable("business_admins",{id:uuid("id").primaryKey().defaultRandom(),businessId:uuid("business_id").notNull().references(()=>businesses.id),userId:uuid("user_id").notNull().references(()=>profiles.id),assignedBy:uuid("assigned_by").references(()=>profiles.id),active:boolean("active").notNull().default(true),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()});
export const openingLedgers=pgTable("opening_ledgers",{id:uuid("id").primaryKey().defaultRandom(),businessId:uuid("business_id").notNull().references(()=>businesses.id),name:text("name").notNull().default("Apertura"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex("opening_ledger_business_idx").on(t.businessId)]);
export const categories=pgTable("categories",{id:uuid("id").primaryKey().defaultRandom(),businessId:uuid("business_id").notNull().references(()=>businesses.id),name:text("name").notNull(),position:integer("position").notNull().default(0),active:boolean("active").notNull().default(true)});
export const openingEntries=pgTable("opening_entries",{id:uuid("id").primaryKey().defaultRandom(),ledgerId:uuid("ledger_id").notNull().references(()=>openingLedgers.id),businessId:uuid("business_id").notNull().references(()=>businesses.id),entryDate:date("entry_date").notNull(),description:text("description").notNull(),categoryId:uuid("category_id").references(()=>categories.id),type:entryType("type").notNull().default("expense"),taxMode:taxMode("tax_mode").notNull().default("included"),taxRate:integer("tax_rate").notNull().default(19),netAmount:bigint("net_amount",{mode:"number"}).notNull(),taxAmount:bigint("tax_amount",{mode:"number"}).notNull(),totalAmount:bigint("total_amount",{mode:"number"}).notNull(),note:text("note"),estimated:boolean("estimated").notNull().default(false),status:entryStatus("status").notNull().default("active"),voidReason:text("void_reason"),createdBy:uuid("created_by").notNull().references(()=>profiles.id),updatedBy:uuid("updated_by").notNull().references(()=>profiles.id),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()});
export const attachments=pgTable("attachments",{id:uuid("id").primaryKey().defaultRandom(),businessId:uuid("business_id").notNull().references(()=>businesses.id),entryId:uuid("entry_id").notNull().references(()=>openingEntries.id),storagePath:text("storage_path").notNull(),fileName:text("file_name").notNull(),mimeType:text("mime_type").notNull(),size:bigint("size",{mode:"number"}).notNull(),createdBy:uuid("created_by").notNull().references(()=>profiles.id),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()});
export const entryChangeLog=pgTable("entry_change_log",{id:uuid("id").primaryKey().defaultRandom(),businessId:uuid("business_id").notNull().references(()=>businesses.id),entryId:uuid("entry_id").notNull().references(()=>openingEntries.id),actorId:uuid("actor_id").notNull().references(()=>profiles.id),before:jsonb("before"),after:jsonb("after"),action:text("action").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()});
export const roleChangeLog=pgTable("role_change_log",{id:uuid("id").primaryKey().defaultRandom(),businessId:uuid("business_id").notNull().references(()=>businesses.id),targetUserId:uuid("target_user_id").notNull().references(()=>profiles.id),actorId:uuid("actor_id").notNull().references(()=>profiles.id),action:text("action").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()});
