create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;
create or replace function private.is_superadmin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce((select is_superadmin and active from public.profiles where id=(select auth.uid())),false) $$;
create or replace function private.administers(target_business uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.business_admins where business_id=target_business and user_id=(select auth.uid()) and active) $$;
revoke all on function public.is_superadmin() from public,anon,authenticated;
revoke all on function public.administers(uuid) from public,anon,authenticated;
grant execute on function private.is_superadmin() to authenticated;
grant execute on function private.administers(uuid) to authenticated;
alter policy "business access" on public.businesses using (private.administers(id) or private.is_superadmin());
alter policy "profile self or superadmin" on public.profiles using (id=(select auth.uid()) or private.is_superadmin());
alter policy "superadmin manages profiles" on public.profiles using (private.is_superadmin()) with check (private.is_superadmin());
alter policy "membership access" on public.business_admins using (user_id=(select auth.uid()) or private.is_superadmin());
alter policy "superadmin manages memberships" on public.business_admins using (private.is_superadmin()) with check (private.is_superadmin());
alter policy "ledger access" on public.opening_ledgers using (private.administers(business_id)) with check (private.administers(business_id));
alter policy "category access" on public.categories using (private.administers(business_id)) with check (private.administers(business_id));
alter policy "entry access" on public.opening_entries using (private.administers(business_id)) with check (private.administers(business_id));
alter policy "attachment access" on public.attachments using (private.administers(business_id)) with check (private.administers(business_id));
alter policy "entry audit read" on public.entry_change_log using (private.administers(business_id));
alter policy "entry audit insert" on public.entry_change_log with check (private.administers(business_id) and actor_id=(select auth.uid()));
alter policy "role audit access" on public.role_change_log using (private.is_superadmin());
alter policy "role audit insert" on public.role_change_log with check (private.is_superadmin() and actor_id=(select auth.uid()));
drop policy if exists "receipt select" on storage.objects; drop policy if exists "receipt insert" on storage.objects; drop policy if exists "receipt delete" on storage.objects;
create policy "receipt select" on storage.objects for select to authenticated using (bucket_id='receipts' and private.administers(((storage.foldername(name))[1])::uuid));
create policy "receipt insert" on storage.objects for insert to authenticated with check (bucket_id='receipts' and private.administers(((storage.foldername(name))[1])::uuid));
create policy "receipt delete" on storage.objects for delete to authenticated using (bucket_id='receipts' and private.administers(((storage.foldername(name))[1])::uuid));
create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,display_name) values(new.id,coalesce(new.email,''),coalesce(new.raw_user_meta_data->>'display_name',split_part(coalesce(new.email,''),'@',1))) on conflict(id) do nothing; return new; end; $$;
revoke all on function private.handle_new_user() from public,anon,authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
